/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author GF63
 */

import javax.swing.*;
import java.awt.CardLayout;
import java.awt.Image;

public class TampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form TampilGambar
     */
    public TampilGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDM = new javax.swing.JButton();
        btnINFORMATIKA = new javax.swing.JButton();
        btnANIMASI = new javax.swing.JButton();
        cover = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDM.setText("DIGITAL MARKETING");
        btnDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMActionPerformed(evt);
            }
        });

        btnINFORMATIKA.setText("INFORMATIKA");
        btnINFORMATIKA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINFORMATIKAActionPerformed(evt);
            }
        });

        btnANIMASI.setText("ANIMASI KOMPUTER ");
        btnANIMASI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnANIMASIActionPerformed(evt);
            }
        });

        cover.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnINFORMATIKA, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnANIMASI)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDM)
                    .addComponent(btnINFORMATIKA)
                    .addComponent(btnANIMASI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cover, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMActionPerformed
        // TODO add your handling code here:
        showImage("D:\\PROJECT\\TampilGambar\\DIGITAL MARKETING.jpg");
    }//GEN-LAST:event_btnDMActionPerformed

    private void btnINFORMATIKAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINFORMATIKAActionPerformed
        // TODO add your handling code here:
        showImage("D:\\PROJECT\\TampilGambar\\ANIMASI KOMPUTER.jpg");
    }//GEN-LAST:event_btnINFORMATIKAActionPerformed

    private void btnANIMASIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnANIMASIActionPerformed
        // TODO add your handling code here:
        showImage("D:\\PROJECT\\TampilGambar\\INFORMATIKA.jpg");
    }//GEN-LAST:event_btnANIMASIActionPerformed

    /**
     * @param args the command line arguments
     */
      private void showImage(String imagePath) {
    try {
        ImageIcon icon = new ImageIcon(imagePath);
        Image image = icon.getImage().getScaledInstance(cover.getWidth(), cover.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(image);

        JLabel imageLabel = new JLabel(scaledIcon);

        // Check if the cover panel has CardLayout
        if (cover.getLayout() instanceof CardLayout) {
            cover.removeAll();
            cover.add(imageLabel);
            CardLayout cardLayout = (CardLayout) cover.getLayout();
            cardLayout.show(cover, "Image");
            cover.revalidate();
            cover.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Error: cover panel does not have CardLayout", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading image: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}


    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new TampilGambar().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnANIMASI;
    private javax.swing.JButton btnDM;
    private javax.swing.JButton btnINFORMATIKA;
    private javax.swing.JPanel cover;
    // End of variables declaration//GEN-END:variables
}
